server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:~/sessionlogin;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 083d2a31e167e084c9edbde1795a6282
            redirect-uri: http://localhost:8080/oauth2/authorization/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org.hibernate.type.descriptor.sql: trace